source "https://rubygems.org"

gem "jekyll", "~> 3.5"
gem "jekyll-theme-architect", "~> 0.1"
gem "kramdown-parser-gfm"
gem 'nokogiri', '~> 1.10'
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem 'jekyll-paginate', '~> 1.1'
end
